name: sihaclik
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  provider:
  google_fonts:
  flutter_localizations:
    sdk: flutter
  timeago:
  camera: ^0.5.8+5
  path_provider:
  path:
  flutter_local_notifications: ^1.4.4+4
  json_annotation:
  shared_preferences:
  dio: ^3.0.10
  dio_http_cache: ^0.2.9
  flutter_secure_storage: ^3.3.3
  # Try to remove it later
  sqflite:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/icons/2.0x/
    - assets/icons/3.0x/

    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

    - assets/fonts/poppins/

    - i18n/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
